export type LawyerProfile = {
  name: string;
  englishName: string;
  role: string;
  office: "서울" | "대전" | "부산";
  registrationNumber: string;
  education: string;
  qualification: string;
  registeredSpecialties: readonly string[];
  practiceAreas: readonly string[];
  profileUrl: string;
  imageUrl: string;
  imageWidth: number;
  imageHeight: number;
  introduction: string;
  bankruptcyRole?: string;
  publicCareer?: readonly string[];
};

export type StaffMember = {
  id: number;
  name: string;
  role: string;
  team: "법률컨설팅팀" | "사건관리팀";
  office: "서울" | "대전" | "부산";
  imageUrl: string;
  imageWidth: number;
  imageHeight: number;
};

export const LAWYER_PROFILE_VERIFIED_DATE = "2026-07-31";
export const LAWYER_PROFILE_VERIFIED_DATE_LABEL = "2026년 7월 31일";

export const lawyers: readonly LawyerProfile[] = [
  {
    name: "김충환",
    englishName: "KIM CHUNG HWAN",
    role: "대표변호사",
    office: "서울",
    registrationNumber: "15977",
    education: "충남대학교 법학전문대학원",
    qualification: "제1회 변호사시험",
    registeredSpecialties: ["도산", "이혼"],
    practiceAreas: ["개인회생", "개인파산·면책", "이혼·가사"],
    profileUrl: "https://www.klaw.or.kr/info/793h43bkwk",
    imageUrl: "/images/people/main_pc_represent_kimchunghwan.png",
    imageWidth: 300,
    imageHeight: 400,
    introduction:
      "개인회생·개인파산 사건의 법률 쟁점과 제출 내용을 검토하고 최종 판단을 담당합니다.",
    bankruptcyRole: "회생·파산 담당변호사",
  },
  {
    name: "허남관",
    englishName: "HEO NAM GWAN",
    role: "파트너변호사",
    office: "부산",
    registrationNumber: "17396",
    education: "충남대학교 법학전문대학원",
    qualification: "제2회 변호사시험",
    registeredSpecialties: ["등기·경매"],
    practiceAreas: ["등기·경매", "부동산"],
    profileUrl: "https://www.klaw.or.kr/info/jl77g53eq2",
    imageUrl: "/images/people/main_pc_lawyer_hernamkwan.png",
    imageWidth: 269,
    imageHeight: 358,
    introduction:
      "부산 사무소에서 등기·경매와 부동산 관련 법률 업무를 담당합니다.",
  },
  {
    name: "우종현",
    englishName: "WOO JONG HYUN",
    role: "파트너변호사",
    office: "대전",
    registrationNumber: "17547",
    education: "충남대학교 법학전문대학원",
    qualification: "제2회 변호사시험",
    registeredSpecialties: [],
    practiceAreas: ["개인회생·파산", "부동산", "민사", "채권추심", "가사"],
    profileUrl: "https://www.klaw.or.kr/info/lawnwoo",
    imageUrl: "/images/people/main_pc_lawyer_woojonghyeon.png",
    imageWidth: 269,
    imageHeight: 358,
    introduction:
      "대전 사무소에서 회생·파산, 부동산, 민사·가사 사건을 수행합니다.",
    publicCareer: ["대전지방법원 개인파산관재인", "대전지방법원 민사조정위원"],
  },
  {
    name: "박혜성",
    englishName: "PARK HYESEONG",
    role: "선임변호사",
    office: "서울",
    registrationNumber: "24195",
    education: "전남대학교 법학전문대학원",
    qualification: "제5회 변호사시험",
    registeredSpecialties: ["가사법", "부동산"],
    practiceAreas: ["부동산", "상속", "이혼·가사", "임대차"],
    profileUrl: "https://www.klaw.or.kr/info/06ry1xw6i7",
    imageUrl: "/images/people/main_pc_lawyer_parkhyeseong.png",
    imageWidth: 269,
    imageHeight: 358,
    introduction:
      "서울 사무소에서 부동산과 가사법을 중심으로 상속·이혼·임대차 사건을 담당합니다.",
  },
] as const;

export const bankruptcyLawyer = lawyers[0];

export const staffTagOptions = [
  "친절",
  "세심",
  "꼼꼼",
  "신뢰",
  "든든",
  "정확",
  "빠름",
  "체계적",
] as const;

// 화면이 새로고침될 때마다 태그가 바뀌지 않도록 구성원 ID를 시드로 사용한다.
// 표시 개수는 2~4개이며, 구성원이 추가되어도 브라우저·서버 렌더 결과가 같다.
export function getStaffTags(id: number): readonly string[] {
  const tagCount = 2 + (id % 3);
  let seed = (id * 53 + 17) % 997;
  const tags: string[] = [];

  while (tags.length < tagCount) {
    const tag = staffTagOptions[seed % staffTagOptions.length];
    if (!tags.includes(tag)) tags.push(tag);
    seed = (seed * 73 + 41) % 997;
  }

  return tags;
}

// 2026-08-03 ERP members 읽기 전용 조회 결과 중 현재 재직하며
// 공개 원본 사진이 확인된 구성원만 표시한다. 개인 연락처와 내부 계정 정보는 포함하지 않는다.
export const staffMembers: readonly StaffMember[] = [
  {
    id: 14,
    name: "박준표",
    role: "과장",
    team: "법률컨설팅팀",
    office: "서울",
    imageUrl: "/images/people/main_member_parkjunpyo.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 15,
    name: "김영찬",
    role: "과장",
    team: "법률컨설팅팀",
    office: "서울",
    imageUrl: "/images/people/main_member_kimyeongchan.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 16,
    name: "방한솔",
    role: "대리",
    team: "법률컨설팅팀",
    office: "서울",
    imageUrl: "/images/people/main_member_banghansol.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 18,
    name: "김현정",
    role: "대리",
    team: "법률컨설팅팀",
    office: "서울",
    imageUrl: "/images/people/main_member_kimhyunjung.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 19,
    name: "이소정",
    role: "대리",
    team: "법률컨설팅팀",
    office: "서울",
    imageUrl: "/images/people/main_member_leesojeong.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 21,
    name: "심웅보",
    role: "대리",
    team: "법률컨설팅팀",
    office: "서울",
    imageUrl: "/images/people/main_member_shimwoongbo.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 32,
    name: "심샛별",
    role: "대리",
    team: "법률컨설팅팀",
    office: "서울",
    imageUrl: "/images/people/main_member_simsaetbyeol.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 38,
    name: "신지용",
    role: "대리",
    team: "법률컨설팅팀",
    office: "서울",
    imageUrl: "/images/people/main_member_shinjiyong.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 47,
    name: "박유은",
    role: "주임",
    team: "법률컨설팅팀",
    office: "서울",
    imageUrl: "/images/people/main_member_parkyueun.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 20,
    name: "박기현",
    role: "주임",
    team: "사건관리팀",
    office: "서울",
    imageUrl: "/images/people/main_member_parkkihyun.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 30,
    name: "김지혜",
    role: "대리",
    team: "사건관리팀",
    office: "서울",
    imageUrl: "/images/people/main_member_kimjihye.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 35,
    name: "공서아",
    role: "주임",
    team: "사건관리팀",
    office: "서울",
    imageUrl: "/images/people/main_member_gongseoa.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 37,
    name: "이보미",
    role: "대리",
    team: "사건관리팀",
    office: "서울",
    imageUrl: "/images/people/main_member_leebomi.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 55,
    name: "이예은",
    role: "대리",
    team: "사건관리팀",
    office: "서울",
    imageUrl: "/images/people/main_member_leeyeeun.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 56,
    name: "백나래",
    role: "대리",
    team: "사건관리팀",
    office: "서울",
    imageUrl: "/images/people/main_member_baeknarae.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 60,
    name: "박성준",
    role: "사원",
    team: "사건관리팀",
    office: "서울",
    imageUrl: "/images/people/main_member_parkseongjun.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 64,
    name: "김동화",
    role: "사원",
    team: "사건관리팀",
    office: "서울",
    imageUrl: "/images/people/main_member_kimdonghwa.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 70,
    name: "황찬호",
    role: "사원",
    team: "사건관리팀",
    office: "서울",
    imageUrl: "/images/people/main_member_hwangchanho.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 22,
    name: "김태준",
    role: "팀장",
    team: "법률컨설팅팀",
    office: "대전",
    imageUrl: "/images/people/main_member_kimtaejun.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 24,
    name: "김지안",
    role: "대리",
    team: "법률컨설팅팀",
    office: "대전",
    imageUrl: "/images/people/main_member_kimjiahn.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 25,
    name: "천왕겸",
    role: "대리",
    team: "법률컨설팅팀",
    office: "대전",
    imageUrl: "/images/people/main_member_cheonwangkyeom.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 39,
    name: "김미진",
    role: "대리",
    team: "법률컨설팅팀",
    office: "대전",
    imageUrl: "/images/people/main_member_kimmijin.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 40,
    name: "박유진",
    role: "대리",
    team: "사건관리팀",
    office: "대전",
    imageUrl: "/images/people/main_member_parkyujin.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 41,
    name: "김민지",
    role: "주임",
    team: "사건관리팀",
    office: "대전",
    imageUrl: "/images/people/main_member_kimminji.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 42,
    name: "신석영",
    role: "주임",
    team: "사건관리팀",
    office: "대전",
    imageUrl: "/images/people/main_member_shinseokyeong.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 58,
    name: "이경은",
    role: "사원",
    team: "사건관리팀",
    office: "대전",
    imageUrl: "/images/people/main_member_leekyungeun.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 59,
    name: "정유민",
    role: "사원",
    team: "사건관리팀",
    office: "대전",
    imageUrl: "/images/people/main_member_jeongyumin.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 66,
    name: "김효준",
    role: "사원",
    team: "사건관리팀",
    office: "대전",
    imageUrl: "/images/people/main_member_kimhyojun.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 73,
    name: "김채림",
    role: "사원",
    team: "사건관리팀",
    office: "대전",
    imageUrl: "/images/people/main_member_kimchaerim.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 74,
    name: "고은혜",
    role: "사원",
    team: "사건관리팀",
    office: "대전",
    imageUrl: "/images/people/main_member_koeunhye.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 23,
    name: "이가현",
    role: "과장",
    team: "법률컨설팅팀",
    office: "부산",
    imageUrl: "/images/people/main_member_leegahyun.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 26,
    name: "정미주",
    role: "팀장",
    team: "법률컨설팅팀",
    office: "부산",
    imageUrl: "/images/people/main_member_jungmiju.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 27,
    name: "권진현",
    role: "과장",
    team: "법률컨설팅팀",
    office: "부산",
    imageUrl: "/images/people/main_member_kwonjinhyun.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 28,
    name: "오미혜",
    role: "대리",
    team: "법률컨설팅팀",
    office: "부산",
    imageUrl: "/images/people/main_member_ohmihye.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 43,
    name: "황윤주",
    role: "대리",
    team: "법률컨설팅팀",
    office: "부산",
    imageUrl: "/images/people/main_member_hwangyoonju.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 44,
    name: "이현유",
    role: "주임",
    team: "사건관리팀",
    office: "부산",
    imageUrl: "/images/people/main_member_leehyeonyu.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 45,
    name: "김희원",
    role: "주임",
    team: "사건관리팀",
    office: "부산",
    imageUrl: "/images/people/main_member_kimheewon.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 46,
    name: "김연주",
    role: "주임",
    team: "사건관리팀",
    office: "부산",
    imageUrl: "/images/people/main_member_kimyeonju.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 61,
    name: "최우성",
    role: "사원",
    team: "사건관리팀",
    office: "부산",
    imageUrl: "/images/people/main_member_choiwoosung.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 63,
    name: "이서영",
    role: "사원",
    team: "사건관리팀",
    office: "부산",
    imageUrl: "/images/people/main_member_leeseoyoung.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 67,
    name: "강혜연",
    role: "사원",
    team: "사건관리팀",
    office: "부산",
    imageUrl: "/images/people/main_member_kanghyeyeon.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 68,
    name: "서화영",
    role: "사원",
    team: "사건관리팀",
    office: "부산",
    imageUrl: "/images/people/main_member_seohwayoung.png",
    imageWidth: 219,
    imageHeight: 188,
  },
  {
    id: 71,
    name: "황정훈",
    role: "사원",
    team: "사건관리팀",
    office: "부산",
    imageUrl: "/images/people/main_member_hwangjunghoon.png",
    imageWidth: 219,
    imageHeight: 188,
  },
] as const;
